apiVersion: v1
kind: Pod
metadata: 
  name: annaotation
  namespace: roboshop
  labels:
    project: roboshop-annaotation
    component: frontend
  annaotation: "this k8 resource"
spec: 
  containers:
    - name: nginx
      image: nginx