apiVersion: v1
kind: Pod
metadata: 
  name: annaotation
  namespace: roboshop
  labels:
    project: roboshop-annaotation
    component: frontend
  annaotations: 
    version: "new version"
spec: 
  containers:
    - name: nginx
      image: nginx