apiVersion: v1
kind: Pod
metadata: 
  name: resource
  namespace: roboshop
spec: 
  containers:
  - name: resource-1
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits: 
        memory: "160 Mi"
        cpu: "100m"