apiVersion: v1
kind: Pod
metadata: 
  name: environment
  namespace: roboshop
spec: 
  containers:
  - name: nginx
    image: nginx
    env:
    -name: project
    value: roboshop
    -name: course
    value: kubernets
    -name: hours
    value: 120