apiVersion: v1
kind: service
metadata:
  name: service-loadblancer
spec:
  type: LoadBlancer
  selector:
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80