apiVersion: v1
kind: ReplicaSet
metadata:
  name: replica-set
spec:
  replica: 2
  selector: 
    matchlabels: 
      project: roboshop
      environment: dev
      tier: frontend
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
